# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from timesync/TimesyncDebug.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TimesyncDebug(genpy.Message):
  _md5sum = "1b9fcff64ffd5b3203e0d1026359e2c2"
  _type = "timesync/TimesyncDebug"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 seq
float64 sensor_time
float64 ros_time
float64 corrected_timestamp
"""
  __slots__ = ['seq','sensor_time','ros_time','corrected_timestamp']
  _slot_types = ['uint32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       seq,sensor_time,ros_time,corrected_timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TimesyncDebug, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.seq is None:
        self.seq = 0
      if self.sensor_time is None:
        self.sensor_time = 0.
      if self.ros_time is None:
        self.ros_time = 0.
      if self.corrected_timestamp is None:
        self.corrected_timestamp = 0.
    else:
      self.seq = 0
      self.sensor_time = 0.
      self.ros_time = 0.
      self.corrected_timestamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I3d().pack(_x.seq, _x.sensor_time, _x.ros_time, _x.corrected_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.seq, _x.sensor_time, _x.ros_time, _x.corrected_timestamp,) = _get_struct_I3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I3d().pack(_x.seq, _x.sensor_time, _x.ros_time, _x.corrected_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.seq, _x.sensor_time, _x.ros_time, _x.corrected_timestamp,) = _get_struct_I3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I3d = None
def _get_struct_I3d():
    global _struct_I3d
    if _struct_I3d is None:
        _struct_I3d = struct.Struct("<I3d")
    return _struct_I3d
