<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>

    <xacro:property name="base_radius" value="0.075"/>
    <xacro:property name="base_length" value="0.104"/>

    <xacro:property name="base_motor_x" value="0.030"/>
    <xacro:property name="base_motor_y" value="0.157"/>
    <xacro:property name="base_motor_z" value="0.030"/> 

    <xacro:property name="wheel_radius" value="0.032"/>
    <xacro:property name="wheel_length" value="0.026"/>

    <xacro:property name="wheel_joint_x" value="0.0000"/>
    <xacro:property name="wheel_joint_y" value="0.0785"/>
    <xacro:property name="wheel_joint_z" value="0.0850"/>

    <xacro:property name="caster_box_x" value="0.04"/>
    <xacro:property name="caster_box_y" value="0.04"/>
    <xacro:property name="caster_box_z" value="0.04"/>

    <xacro:property name="caster_box_joint_x" value="0.055"/>

    <xacro:property name="caster_radius" value="0.0125"/> <!-- wheel_radius - ( base_length/2 - wheel_joint_z) -->

    <xacro:property name="caster_joint_x" value="0.055"/>

    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>  
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>
    
    <!-- Macro for robot wheel -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="${-wheel_joint_x} ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster box -->
    <xacro:macro name="caster_box" params="prefix reflect">
        <joint name="${prefix}_caster_box_joint" type="fixed">
            <origin xyz="${reflect*caster_box_joint_x} 0 ${-(base_length/2 + caster_box_z/2)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_box_link"/>
        </joint>

        <link name="${prefix}_caster_box_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                     <box size="${caster_box_x} ${caster_box_y} ${caster_box_z}" />
                </geometry>
                <material name="yellow" />
            </visual>
        </link>
    </xacro:macro>

    <!-- Macro for robot caster -->
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(base_length/2 + caster_box_z + caster_radius)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="mbot_base">

        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${base_length/2 + caster_box_z + caster_radius*2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${base_radius}" length = "${base_length}"/>
                </geometry>
                <material name="yellow" />
            </visual>
        </link>

        <joint name="base_motor_joint" type="fixed">
            <origin xyz="0 0 -${base_length/2 + base_motor_z/2 }" rpy="0 0 0" />        
            <parent link="base_link"/>
            <child link="base_motor_link" />
        </joint>

        <link name="base_motor_link">
            <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_motor_x} ${base_motor_y} ${base_motor_z}" />
            </geometry>
            </visual>
        </link>

        <wheel prefix="left" reflect="-1"/>
        <wheel prefix="right" reflect="1"/>
        <caster_box prefix="front" reflect="1"/>
        <caster_box prefix="back" reflect="-1"/>
        <caster prefix="front" reflect="1"/>
        <caster prefix="back" reflect="-1"/>
        
    </xacro:macro>
</robot>
